import { Foods } from 'src/app/auth/shared/models/food';

export const data_list: Foods[] = [

  {
    id: 1,
    price: 120,
    name: 'Теплий салат',
    favorite: false,
    tags:['Салат', 'Обід', 'Боул', "Риба"],
    imageUrl: '../../../../../assets/1.jpg',
    cookTime: '10-20',
    description:['Теплий салат з рибою та овочами'],
},

  {
    id: 2,
    price: 100,
    name: 'Ранковий боул',
    favorite: true,
    tags: ['Сніданок', 'Обід', 'Боул'],
    imageUrl: '../../../../../assets/2.jpg',
    cookTime: '20',
    description:['Боул з овочами та сиром моцарелою'],
},

  {
    id: 3,
    price: 150,
    name: 'Запечена риба',
    favorite: false,
    tags:['Обід', 'Риба'],
    imageUrl: '../../../../../assets/3.jpg',
    cookTime: '40',
    description:['Запечена сьомга під овочами'],
  },

  {
    id: 4,
    price: 130,
    name: 'Поке з тунцем',
    favorite: true,
    tags:['Боул', 'Обід', 'Риба'],
    imageUrl: '../../../../../assets/4.jpg',
    cookTime: '20',
    description:['Поке з тунцем, манго та авокадо'],
},

  {
    id: 5,
    price: 90,
    name: 'Китайська лапша',
    favorite: false,
    tags:['Боул', 'Обід', "М'ясо"],
    imageUrl: '../../../../../assets/5.jpg',
    cookTime: '35',
    description:["Скляна лапша з гов'ядиною та овочами"],
  },

  {
    id: 6,
    price: 80,
    name: 'Боул с куркою та овочами',
    favorite: false,
    tags:[ 'Обід', "М'ясо", 'Сніданок'],
    imageUrl: '../../../../../assets/6.jpg',
    cookTime: '25',
    description:['Боул з куркою, салатом та нутом'],
  },

  {
    id: 7,
    price: 170,
    name: 'Запечені равлики',
    favorite: false,
    tags:['Екзотика', 'Обід'],
    imageUrl: '../../../../../assets/7.jpg',
    cookTime: '40',
    description:['Равлики в лимонному соусі'],
  },

  {
    id: 8,
    price: 160,
    name: 'Спрінг-роли з лососем',
    favorite: true,
    tags:['Спрінг-роли', 'Обід', 'Риба'],
    imageUrl: '../../../../../assets/8.jpg',
    cookTime: '40',
    description:['Спрінг-роли з лососем та ікрою'],
  },

  {
    id: 9,
    price: 140,
    name: 'Спрінг-роли з овочами',
    favorite: false,
    tags:['Спрінг-роли', 'Обід', 'Веган'],
    imageUrl: '../../../../../assets/9.jpg',
    cookTime: '40',
    description:['Спрінг-роли зі свіжими овочами'],
  },

  {
    id: 10,
    price: 170,
    name: 'Спрінг-роли з креветкою',
    favorite: true,
    tags:['Спрінг-роли', 'Обід'],
    imageUrl: '../../../../../assets/10.jpg',
    cookTime: '40',
    description:['Спрінг-роли зі свіжими овочами'],
  },

  {
    id: 11,
    price: 100,
    name: 'Суп з морепродуктами',
    favorite: false,
    tags:['Обід', 'Риба'],
    imageUrl: '../../../../../assets/11.jpg',
    cookTime: '30',
    description:['Свіжий суп з морськими мешканцями'],
  },

  {
    id: 12,
    price: 140,
    name: 'Окрошка',
    favorite: true,
    tags:['Веган', 'Обід', 'Риба', "М'ясо"],
    imageUrl: '../../../../../assets/12.jpg',
    cookTime: '20',
    description:['Окрошка веган, з куркою або лососем на вибір'],
  },

  {
    id: 13,
    price: 90,
    name: 'Роли Веган',
    favorite: false,
    tags:['Веган', 'Обід', 'Роли'],
    imageUrl: '../../../../../assets/13.jpg',
    cookTime: '40',
    description:['Веган роли з вегутаріанською філадельфією та авокадо'],
  },

  {
    id: 14,
    price: 160,
    name: 'Роли з вугрем',
    favorite: false,
    tags:['Обід', 'Риба', 'Роли'],
    imageUrl: '../../../../../assets/14.jpg',
    cookTime: '40',
    description:['Роли з вугрем та грушею'],
  },

  {
    id: 15,
    price: 170,
    name: 'Роли Каліфорнія',
    favorite: true,
    tags:['Роли', 'Обід', 'Риба'],
    imageUrl: '../../../../../assets/15.jpg',
    cookTime: '40',
    description:['Роли Каліфорнія з філадельфією'],
  },

  {
    id: 16,
    price: 200,
    name: 'Суші асорті',
    favorite: false,
    tags:['Роли', 'Обід', 'Риба'],
    imageUrl: '../../../../../assets/16.jpg',
    cookTime: '45',
    description:['Суші з тунцем та лососем'],
  },

  {
    id: 17,
    price: 40,
    name: 'Оранж капучіно',
    favorite: false,
    tags:['Гарячі напої'],
    imageUrl: '../../../../../assets/17.jpg',
    cookTime: '10',
    description:['Капучіно з апельсиновим соком'],
  },

  {
    id: 18,
    price: 35,
    name: 'Еспресо',
    favorite: true,
    tags:['Гарячі напої'],
    imageUrl: '../../../../../assets/18.jpg',
    cookTime: '7',
    description:['Еспресо з якісного зерна'],
  },

  {
    id: 19,
    price: 40,
    name: 'Капучіно',
    favorite: true,
    tags:['Гарячі напої'],
    imageUrl: '../../../../../assets/19.jpg',
    cookTime: '10',
    description:['Капучіно з якісного зерна та молоком на вибір'],
    },

  {
    id: 20,
    price: 50,
    name: 'Лате',
    favorite: true,
    tags:['Гарячі напої'],
    imageUrl: '../../../../../assets/20.jpg',
    cookTime: '10',
    description:['Лате з якісного зерна та молоком на вибір'],
  },

  {
    id: 21,
    price: 50,
    name: 'Какао',
    favorite: false,
    tags:['Гарячі напої'],
    imageUrl: '../../../../../assets/21.jpg',
    cookTime: '10',
    description:['Тепле какао з зефіром'],
    },
  {
    id: 22,
    price: 40,
    name: 'Амерікано з молоком',
    favorite: false,
    tags:['Гарячі напої'],
    imageUrl: '../../../../../assets/22.jpg',
    cookTime: '7',
    description:['Амерікано з молоком на вибір'],
  },

  {
    id: 23,
    price: 60,
    name: 'Фрапе',
    favorite: false,
    tags:['Гарячі напої'],
    imageUrl: '../../../../../assets/23.jpg',
    cookTime: '10',
    description:['Кофе з морозивом'],
  },

  {
    id: 24,
    price: 50,
    name: 'Грейпфрутове смузі',
    favorite: false,
    tags:['Смузі'],
    imageUrl: '../../../../../assets/24.jpg',
    cookTime: '10',
    description:['Грейпфрутове смузі'],
  },

  {
    id: 25,
    price: 50,
    name: 'Полуничне смузі',
    favorite: false,
    tags:['Смузі'],
    imageUrl: '../../../../../assets/25.jpg',
    cookTime: '10',
    description:['Полуничне смузі'],
  },

  {
    id: 26,
    price: 50,
    name: 'Цитрусове смузі',
    favorite: false,
    tags:['Смузі'],
    imageUrl: '../../../../../assets/26.jpg',
    cookTime: '10',
    description:['Цитрусове смузі'],
  },

  {
    id: 27,
    price: 70,
    name: 'Зелене смузі',
    favorite: false,
    tags:['Смузі', 'Екзотика'],
    imageUrl: '../../../../../assets/27.jpg',
    cookTime: '15',
    description:['Смузі з ківі та банану'],
  },

  {
    id: 28,
    price: 70,
    name: 'Жовте смузі',
    favorite: false,
    tags:['Смузі', 'Екзотика'],
    imageUrl: '../../../../../assets/28.jpg',
    cookTime: '15',
    description:['Смузі з банану та грейпфруту'],
  },

  {
    id: 29,
    price: 70,
    name: 'Помаранчеве смузі',
    favorite: false,
    tags:['Смузі'],
    imageUrl: '../../../../../assets/29.jpg',
    cookTime: '15',
    description:['Смузі з персику та банану'],
  },

  {
    id: 30,
    price: 100,
    name: 'pizza',
    favorite: false,
    tags:['Тропічний чай'],
    imageUrl: '../../../../../assets/30.jpg',
    cookTime: '15',
    description:['Чай з тропічними фруктами'],
  },

  {
    id: 31,
    price: 100,
    name: 'Зелений чай',
    favorite: false,
    tags:['Чай'],
    imageUrl: '../../../../../assets/31.jpg',
    cookTime: '15',
    description:['Чай з жасміном зелений'],
  },

  {
    id: 32,
    price: 100,
    name: 'Чорний чай',
    favorite: false,
    tags:['Чай'],
    imageUrl: '../../../../../assets/32.jpg',
    cookTime: '15',
    description:['Чорний чай з фруктами'],
  },

  {
    id: 33,
    price: 100,
    name: 'Цитрусовий чай',
    favorite: false,
    tags:['Чай'],
    imageUrl: '../../../../../assets/33.jpg',
    cookTime: '15',
    description:['Чай з лимоном та лаймом'],
  },

  {
    id: 34,
    price: 100,
    name: 'Гречишний чай',
    favorite: false,
    tags:['Чай'],
    imageUrl: '../../../../../assets/34.jpg',
    cookTime: '15',
    description:['Натуральний гречишний чай'],
  },

  {
    id: 35,
    price: 70,
    name: 'Ягідний лимонад',
    favorite: false,
    tags:['Лимонад'],
    imageUrl: '../../../../../assets/35.jpg',
    cookTime: '10',
    description:['Лимонад з полуницею та лохиною'],
  },

  {
    id: 36,
    price: 70,
    name: 'Кокосовий лимонад',
    favorite: false,
    tags:['Лимонад'],
    imageUrl: '../../../../../assets/36.jpg',
    cookTime: '10',
    description:['Лимонад з кокосом'],
  },

  {
    id: 37,
    price: 70,
    name: 'Лимонад зі спіруліною',
    favorite: false,
    tags:['Лимонад', 'Екзотика'],
    imageUrl: '../../../../../assets/37.jpg',
    cookTime: '10-20',
    description:['italy'],
  },

  {
    id: 38,
    price: 60,
    name: 'Цитрусове мрозиво',
    favorite: false,
    tags:['Морозиво', 'Веган'],
    imageUrl: '../../../../../assets/38.jpg',
    cookTime: '10',
    description:['Натуральне морозиво з цитрусами'],
  },

  {
    id: 39,
    price: 80,
    name: 'Морозиво зі спіруліною',
    favorite: true,
    tags:['Морозиво', 'Веган', 'Екзотика'],
    imageUrl: '../../../../../assets/39.jpg',
    cookTime: '10',
    description:['Натуральне морозиво зі зеленою водорістю'],
  },

  {
    id: 40,
    price: 140,
    name: 'Сирники',
    favorite: true,
    tags:['Сніданок', 'Веган'],
    imageUrl: '../../../../../assets/40.jpg',
    cookTime: '35',
    description:['Сирники з сиру або тофу'],
  }
]
